Arenaworld: "Arena"
Spawn1:
   X: 100
   Y: 100
   Z: 100
   Pitch: 100
   Yaw: 100
Spawn2: 
   X: 150
   Y: 150
   Z: 150
   Pitch: 100
   Yaw: 100
Lobby: 
   World: "world"
   X: 100
   Y: 100
   Z: 100
   Pitch: 100
   Yaw: 100
Database:
  Host: localhost
  Port: 3306
  Database: db
  User: username
  Password: passy